### PR TITLE
Prepare v0.10.0 release

### PR DESCRIPTION
**Pull request by tigrannajaryan**

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@tpaschalis FYI.

**Review by jaronoff97 — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@tpaschalis looks like you are not an OpenTelemetry github org member, so I can't add you as a reviewer to PRs. Please consider applying for membership: https://github.com/open-telemetry/community/blob/main/community-membership.md

I will support as a sponsor.

**Comment by tigrannajaryan** [comment]
Release drafted and ready to go: https://github.com/open-telemetry/opamp-spec/releases/edit/untagged-67d37f6d16e56997e757

**Comment by tigrannajaryan** [comment]
@andykellr I will be out for the next 2 weeks. Please feel free to review/merge and make the release.

**Review by andykellr — APPROVED** [review]

**Comment by tpaschalis** [comment]
Thank you Tigran, just saw the message, will consider doing so! 🙏
Also, now that the spec change is out, I can go ahead for the relevant implementation in opamp-go as well.

**Pull request merged**
